spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Qiu19871127@&
  batch:
    job:
      enabled: true
    initialize-schema: always
