server:
  port: 8085
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#  cloud:
#    gateway:
#      routes:
#        - id: neo_route
#          uri: http://www.ityouknow.com
#          predicates:
#            - Path=/spring-cloud #路径匹配
#            - After=2019-11-15T13:06:06+08:00[Asia/Shanghai]  # 时间匹配 >=
#            - Before=2019-12-20T06:06:06+08:00[Asia/Shanghai] # 时间匹配 <=
#            - Between=2019-01-20T06:06:06+08:00[Asia/Shanghai], 2020-01-20T06:06:06+08:00[Asia/Shanghai] #中间

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug