eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-service
server:
  port: 8081
zuul:
  retryable: true
ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0
#zuul:
#  routes:
#    hello:
#      path: /**
#      serviceId: spring-cloud-web
#      url: http://localhost:9000/